### ISSUE TITLE
Potential bug - Missing IP ranges in datacenters

### ISSUE THREAD

**Issue by ptibom** [Umkus/ip-index#20]
I couldn't reopen the previous issue so here goes:
https://github.com/Umkus/ip-index/issues/19#issuecomment-988226267

> The following IP range belonging to 42473 is not in the datacenter table, despite the ASN being listed in matches as a datacenter.
> 
> `131 | 2204368896 | 2204369919 | 42473`
> 
> ![missing-range](https://user-images.githubusercontent.com/7933595/145099305-cda379c8-dfdb-4f39-a59d-3553233088d1.png)
> 
> This might be a bug, but I have not checked if this is a problem for other ranges.
> 
> Here's a test IP: 2204369629.

_Originally posted by @ptibom in https://github.com/Umkus/ip-index/issues/19#issuecomment-988226267_

**Comment by Umkus** [comment]
Hello, yes, this looks strange, I'm checking what's up.

**Comment by Umkus** [comment]
Should be working fine now.
