### ISSUE TITLE
License file is missing

### ISSUE THREAD

**Issue by yassinedoghri** [Umkus/ip-index#26]
Hey, I discovered this great project coming from https://github.com/client9/ipcat/issues/154

Went through the list of datasets that that are provided and - from what I gathered - they can be used as a replacement from the unmaintained https://github.com/client9/ipcat

One thing seems missing though, I couldn't find any License file. It would let developers know how they may or may not use this project.

**client9/ipcat** uses the [GPL v3 License](https://github.com/client9/ipcat/blob/master/LICENSE) to "prevent commercial data providers from scooping up this data without compensation or attribution".

Here's a great website on the subject: https://choosealicense.com/

**Comment by ptibom** [comment]
Just want to throw in that a MIT or Apache license would be nice, for simplicity.

**Comment by Umkus** [comment]
Thanks! Added the [GPL v3 License](https://github.com/Umkus/ip-index/blob/master/LICENSE).
