### ISSUE TITLE
AS398083 missing in asn-ip

### ISSUE THREAD

**Issue by Sainan** [Umkus/ip-index#30]
I know this is a different project, but I can't open an issue over there, and I assume as a result of this issue, 5.133.124.0/24 will cause issues with this project.

This isn't by far the only AS that is affected, the following numbers and possibly more are missing: 940, 1636, 3577, 4879, 6485, 6565, 7363, 10425, 10475, 10931, 10981, 11011, 11044, 11091, 11223, 11316, 11490, 11610, 11636, 11825, 11945, 11967, 11969, 11974, 12176, 12240, 13224, 13317, 13339, 13342, 13492, 13520, 13717, 13980, 14046, 14076, 14350, 14428, 14439, 14461, 14545, 14552, 14594, 14605, 14651, 14889, 15037, 15115, 15178, 15182, 15200, 15220, 15329, 15804, 16615, 16666, 16769, 16804, 16809, 17341, 18604, 18691, 18775, 18781, 18796, 18798, 18805, 18821, 18976, 19023, 19081, 19140, 19142, 19176, 19330, 19359, 19507, 19521, 19533, 19658, 19700, 19708, 19926, 20089, 20118, 20190, 20200, 20227, 20421, 20443, 20447, 21584, 21666, 21695, 21714, 21861, 21986, 22063, 22160, 22226, 22271, 22272, 22484, 22538, 22539, 22694, 22733, 22736, 22743, 22774, 22830, 23021, 23176, 23190, 23194, 23288, 23357, 23411, 23448, 23507, 25568, 25600, 25641, 25647, 25800, 25831, 25922, 25978, 26015, 26016, 26018, 26051, 26137, 26140, 26286, 26295, 26341, 26345, 26520, 26643, 26663, 26682, 26701, 26712, 26759, 26799, 26861, 26922, 26986, 27174, 27180, 27247, 27289, 27291, 27335, 27384, 27426, 27470, 28102, 29763, 29829, 29855, 29987, 30004, 30006, 30037, 30104, 30155, 30265, 30442, 30550, 30654, 30699, 31781, 31813, 32021, 32042, 32103, 32121, 32187, 32203, 32282, 32346, 32358, 32467, 32497, 32534, 32581, 32596, 32772, 32842, 33017, 33023, 33042, 33051, 33123, 33137, 33232, 33245, 33394, 33417, 33484, 33625, 33628, 33684, 33732, 35948, 36002, 36267, 36283, 36357, 36465, 36774, 36893, 36900, 36911, 36928, 36979, 37034, 37155, 37169, 37320, 37338, 37442, 37475, 37476, 37544, 37555, 37591, 37703, 39991, 40186, 40255, 40279, 40340, 40503, 40600, 40687, 40745, 40751, 40779, 40909, 40920, 46086, 46123, 46161, 46226, 46228, 46233, 46355, 46501, 46559, 46614, 46673, 46766, 46772, 46815, 46876, 46916, 47044, 47069, 47086, 52761, 53298, 53367, 53419, 53552, 53657, 53715, 53751, 53771, 53775, 53854, 53929, 53947, 54148, 54209, 54218, 54231, 54262, 54278, 54309, 54338, 54424, 54427, 54517, 54518, 54590, 54752, 54753, 54776, 54787, 55289, 62711, 62828, 63092, 63190, 63198, 63305, 63387, 63390, 63401, 64203, 64257, 65656, 65999, 227171, 261050, 264245, 264379, 264493, 265039, 268652, 269062, 269948, 327869, 327928, 327933, 328007, 328226, 328369, 393266, 393305, 393314, 393320, 393322, 393377, 393446, 393491, 393493, 393588, 393866, 394076, 394156, 394183, 394293, 394376, 394402, 394519, 394607, 394721, 394787, 394788, 394856, 394879, 394936, 394939, 395270, 395281, 395350, 395438, 395514, 395858, 395898, 396015, 396330, 396993, 397096, 397124, 397186, 397306, 398083, 398118, 1440665

**Comment by Umkus** [comment]
Hello, thanks, [5.133.124.0](https://www.ip2location.com/demo/5.133.124.0) is indeed DCH.
Most if not all others are "Commercial" or "Fixed Line ISP" usage types (if allocated), though.
