### ISSUE TITLE
Fetching new versions daily

### ISSUE THREAD

**Issue by bfelbo** [Umkus/ip-index#34]
Hi, thanks for a great repo! Curious to hear how you'd recommend fetching daily versions when using the Docker image in production?

It'd be simple to spin down the Docker, grab the latest image and spin that up. However, we'd of course like to do the daily update of the IP list w/o downtime. Have you considered adding that functionality to the Docker image?

**Comment by Umkus** [comment]
Hello!
Easiest daily solution is to only update and restart the node docker image. That's where the actual logic lives. The nginx image is just a reverse proxy and should handle 99% of requests from its cache. When the cache expires (24h) it would refresh it from a previously updated node image.

Btw, you don't need to stop a container to update the image. Just pull and re-run. For docker compose it's even a one-liner  `docker compose up --pull`
