### ISSUE TITLE
False positive

### ISSUE THREAD

**Issue by hsnoil** [Umkus/ip-index#40]
This one seems to be a false positive:

394330

It belongs to LTD Broadband

https://www.ip2location.com/as394330

https://ltdbroadband.com/

They don't seem to offer any vpn or datacenter services and are clearly a fiber/wireless ISP

Also, is there any info how the list is made, you just do a check on one of the 3 and if it shows up you mark it? Maybe something like a confidence score can limit false positives?

**Comment by Umkus** [comment]
Right now this is the way it's checked, yes.
Originally when the bulk of the list was put together it was with grep-ing DCH-like descriptions in ASNs also by merging other lists and a lot of manual work.
Not sure confidence score is applicable at this moment. I did think about doing a control run-through for all ASNs in the list (`asns_dcs.csv`).

**Comment by hsnoil** [comment]
I mean like if say you use 3 providers and all 3 show them as proxy, you set a high confidence score. If only one of them shows it the score can be lower. Maybe add more than 1 ip to the search for further increase in confidence. Like checking a random IP in the ASN block once a month to further increase/decrease confidence. Other lists you can treat same as a provider, and manual can probably have near full confidence.

**Comment by Umkus** [comment]
Unfortunately there's no automated checks to implement something like you describe.
I check IPs manually each time before adding corresponding ASN to the list.

**Comment by Umkus** [comment]
394330 is no more part of the list
