### ISSUE TITLE
AS29447

### ISSUE THREAD

**Issue by MyWay** [Umkus/ip-index#44]
Hi, it seems that AS29447 is incorrectly reported.

**Comment by Umkus** [comment]
Fixed in #46

**Comment by ghost** [comment]
> Fixed in #46

Is it really fixed if you readded the ASN in the [next commit](https://github.com/Umkus/ip-index/commit/cffbf55eedb7832a0b204837224a426d2abe695d)? (or, well, it looks like the script responsible for updates might have done that, in which case, would it be possible to prevent the ASN from being readded?)

**Comment by Umkus** [comment]
Looks like it got added automatically, yes.
I guess I'll have to add a whitelist or something.

**Comment by Umkus** [comment]
This should be fixed now.
